name: Build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Sätt upp Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Bygg med Maven
        run: mvn clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Kör tester
        run: mvn test
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}